### PR TITLE
Postconf_master: Fix #9

### LINKED ISSUE #9: postconf_master is only parsed on a Puppet run *following* Postfix install
On an initial Puppet run (i.e. from a vanilla OS) using `puppet apply` locally (masterless):

```
Error: Could not find a suitable provider for postconf_master
```

On the following Puppet run:
```
Notice: /Stage[main]/Custom::Profile::Clamav/Postconf_master[amavis/unix]/ensure: created
Notice: /Stage[main]/Custom::Profile::Clamav/Postconf_master[127.0.0.1:10025/inet]/ensure: created
```

### PR DESCRIPTION
**Pull request by craigwatson**

### CODE REVIEW

**Comment by oxc** [comment]
The confine is there for a reason, postfix before 2.11 does not provide the postconf functions needed to modify master.cf entries.

**Comment by craigwatson** [comment]
I think there's other ways of doing this - perhaps by flagging in documentation or even in the manifests themselves somehow.

The root issue is the chicken-and-egg of fact vs code evaluation. If the fact returns that Postfix is not installed, then the module should account for that, and not break - perhaps the logic should be moved into the `postconf_master` code itself (e.g. to call out to Postfix to get the version before running).

Either way, the confine is IMO the wrong way to go.

**Comment by fraenki** [comment]
> The confine is there for a reason, postfix before 2.11 does not provide the postconf functions needed to modify master.cf entries.

I like the approach of preventing the code from running on unsupported versions, but I've just realized that Postfix 2.10 is [EOL](http://www.postfix.org/announcements/postfix-3.1.4.html) for 1+ year now.

Maybe it's the right time to remove all pre-2.11 safekeeping from the code and just add a note to the README.

**Comment by oxc** [comment]
Thanks @fraenki, for checking. That makes sense, I guess running into an error on an outdated version is acceptable in this case, especially since it's unlikely that there will ever be another provider implementation for postfix_master resources (that would wrongly be ignored without the confine).

**Comment by craigwatson** [comment]
Thanks for the comments, I’m happy to add code into the `postconf_master` provider if we need to keep a `confine`-like mechanism?

**Comment by oxc** [comment]
I don't think that's necessary, but I would appreciate a more descriptive (and self-contained) commit message.

**Comment by craigwatson** [comment]
Apologies for the delay, I've just pushed an updated commit message :)

**Comment by oxc** [comment]
Thanks! I added some changelog and a more detailed explanation in the commit comment, so I authored the changeset myself.

**Pull request closed without merging**
